# Jekyll Defaults
title: Enjoy Code
description:
baseurl: # the subpath of your site, e.g. /blog
port: 4001
url: "https://s-petit.github.io"
github:
  url:               "https://s-petit.github.io"
author:
  name:              "Stéphane Petit"
  email:             "spetit@enjoycode.fr"
  twitter:           "spetit95"
  github:            "s-petit"
  linkedin:          "stéphane-petit-a61b8b99"
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 5
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
disqus: "enjoy-code"
navigation:
- text: A propos de l'auteur
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/

# May be useful in order to deploy future posts in localhost
future: true

